Adding the Canvas File for Hacktoberfest 2022
zero-to-mastery/canvas-2022 pull request #135
Opened 2022-10-11 05:51 UTC by anayatkhan1

# Zero To Mastery - Canvas 2022 🎉🎉

## PR contains:
- Hey, I'm a Active contributor. I have done Canvas Project (MousyBubble) for Hacktoberfest 2022, it is a Canvas Animation i hope you like it my contribution 🤜

## Breaking changes
-  None

## Screenshots
![icons](https://user-images.githubusercontent.com/73161735/195006823-55a69d49-5816-489e-8c3f-50cdfc152ea8.gif)

2022-10-11 17:44 UTC, anayatkhan1 commented
is it important to keep the js file name is art.js, because i actually make this file name is script.js. is everything is alright

2022-10-12 17:30 UTC, sophiabrandt requested changes

2022-10-12 17:30 UTC, sophiabrandt commented on src/art/AnayatCanvas/script.js
> +// Below Code is for practicing for making animation, canvas and So on.
Please remove unused code

2022-10-12 17:30 UTC, sophiabrandt commented on src/art/AnayatCanvas/styles.css
> +/* canvas{
Same here.

2022-10-12 18:00 UTC, anayatkhan1 commented on src/art/AnayatCanvas/script.js
> +// console.log(circleArray);
i remove the unused code

2022-10-13 19:17 UTC, merged