Canvas art
zero-to-mastery/canvas-2022 pull request #159
Opened 2022-10-15 13:39 UTC by BGS89

# Zero To Mastery - Canvas 2022 🎉🎉

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## PR contains:
A happy face(Please be as descriptive as possible) 🤜

## Breaking changes
None

## Screenshots
![icon](https://user-images.githubusercontent.com/79923176/195989480-7948eb0d-1961-41d2-9c2b-4211f9946dd8.png)

2022-10-15 18:21 UTC, sophiabrandt requested changes
`meta.json` missing, plus see other comments.

2022-10-15 18:21 UTC, sophiabrandt commented on src/art/BGS89/index.html
> +    <title></title>
Please fill out the title.

2022-10-15 18:21 UTC, sophiabrandt commented on src/art/BGS89/script.js
> +        // ctx.fillStyle = 'rgb(255, 0, 0)';
Please remove unused code.

2022-10-15 18:21 UTC, sophiabrandt commented on src/art/BGS89/style.css
> +    /* background: rgb(0, 28, 85); */
Same here.

2022-10-16 10:06 UTC, BGS89 commented
I have made the changes requested

2022-10-16 12:40 UTC, merged