Added Sattyam Samania in art folder
zero-to-mastery/canvas-2022 pull request #173
Opened 2022-10-17 14:13 UTC by SattyamSamania

# Zero To Mastery - Canvas 2022 🎉🎉

## PR contains:
- I Have Created a Simple 2D Art using Html canvas, Css and Javascript. Please merge my PR under Hacktoberfest Label.

## Breaking changes
- None

## Screenshots
- 
![Canvas](https://user-images.githubusercontent.com/67833888/196200077-6881b228-3aeb-45f0-be59-e7b88dbb19fa.png)

2022-10-17 17:56 UTC, sophiabrandt commented
`meta.json` is missing, please add it with your information.

2022-10-18 04:39 UTC, sophiabrandt requested changes

2022-10-18 04:39 UTC, sophiabrandt commented on src/art.js
> +
Please do not change anything in this file.
See step 10 in the guide:
> Please keep src/art.js as it is. If you follow step 10 above, a script will add your art automatically after your PR is merged

2022-10-18 08:36 UTC, SattyamSamania commented
Hey @sophiabrandt I have made changes in the src/art.js. you can have a look at it. Thank you for the correction

2022-10-19 10:25 UTC, merged