added aproaching animal
zero-to-mastery/canvas-2022 pull request #186
Opened 2022-10-18 20:35 UTC by anshuman-nandan

# Zero To Mastery - Canvas 2022 🎉🎉

2022-10-19 05:39 UTC, betiniakarandut commented on src/art/anshuman3/script.js
> +// c=0;
Please remove unuseful codes or line here (line 12). Or you can add the effect of line 12 if uncommented. Thank you

2022-10-19 05:39 UTC, betiniakarandut commented on src/art/anshuman3/script.js
> +    // charcontainer.fillRect(c,50,100,100)
Same here. Remove the unused lines of codes or  comment on the effect it may have if uncommented (lines 16 and 17)

2022-10-20 09:11 UTC, sophiabrandt requested changes

2022-10-20 09:11 UTC, sophiabrandt commented on src/art/anshuman3/script.js
> +charimg.src = "sprite.png";
Please provide the license to the image you used, so that we can be sure that we don't violate copyright.

2022-10-20 09:16 UTC, sophiabrandt requested changes

2022-10-20 09:17 UTC, sophiabrandt commented
Please fill out the request template.

2022-10-26 12:50 UTC, MattCSmith commented
Closing due to unresolved change request. Feel free to resolve and reopen.

2022-10-26 12:50 UTC, closed without merging