randomized ray length and rotation speed
zero-to-mastery/canvas-2022 pull request #231
Opened 2022-10-26 07:44 UTC by chang-hs

# Zero To Mastery - Canvas 2022 🎉🎉

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## PR contains:
Simulation of fireworks with randomized starting position, ray number, ray length, and rotation speed

## Breaking changes
None

## Screenshots
![icon](https://user-images.githubusercontent.com/8831119/197965283-cc1131af-1608-4902-b747-a5f108efc561.png)

2022-10-26 07:45 UTC, chang-hs commented
Hi, I added some more randomization of ray length and rotation speed.
I appreciate your review. Thank you.

2022-10-26 11:42 UTC, sophiabrandt requested changes

2022-10-26 11:42 UTC, sophiabrandt commented on src/art/chang-hs/script.js
> +// function draw(){
Please don't commit code that you commented out.

2022-10-26 22:55 UTC, chang-hs commented
Thanks for your review. I deleted the commented-out part. Would you review it again?

2022-10-27 18:35 UTC, auxfuse approved these changes
LGTM Thanks for making the changes 🤜

2022-10-27 18:35 UTC, merged